version: 2

sources:
  - name: bronze
    database: "{{ env_var('BIGQUERY_PROJECT_ID') }}"
    schema: "{{ env_var('BIGQUERY_BRONZE_DATASET') }}"
    tables:
      - name: nytimes_articles
        meta:
          dagster:
            asset_key: ["bronze", "nytimes_articles"]
      - name: x_conversations
        meta:
          dagster:
            asset_key: ["bronze", "x_conversations"]
      - name: x_conversation_posts
        meta:
          dagster:
            asset_key: ["bronze", "x_conversation_posts"]

  - name: silver
    database: "{{ env_var('BIGQUERY_PROJECT_ID') }}"
    schema: "{{ env_var('BIGQUERY_SILVER_DATASET') }}"
    tables:
      - name: conversation_classifications
        meta:
          dagster:
            asset_key: ["silver", "conversation_classifications"]
      - name: post_narrative_associations
        meta:
          dagster:
            asset_key: ["silver", "post_narrative_associations"]
      - name: user_geolocations
        meta:
          dagster:
            asset_key: ["silver", "user_geolocations"]
  - name: prototypes
    database: "{{ env_var('BIGQUERY_PROJECT_ID') }}"
    schema: "{{ env_var('BIGQUERY_PROTOTYPES_DATASET') }}"
    tables:
      - name: conversation_event_summaries
        identifier: conversation_event_summary_output
        meta:
          dagster:
            asset_key: ["prototypes", "conversation_event_summary"]
