name: "climate_resilience_analytics"
version: "0.1.0"
require-dbt-version: ">=1.8.6"
config-version: 2

profile: climate_resilience_analytics

models:
  climate_resilience_analytics:
    +materialized: table
