version: 2

sources:
  - name: data_lake
    database: "{{ env_var('BIGQUERY_PROJECT_ID') }}"
    schema: "{{ env_var('BIGQUERY_DATASET') }}"
    tables:
      - name: conversation_classifications
        meta:
          dagster:
            asset_key: ["enrichments", "conversation_classifications"]
      - name: nytimes_articles
        meta:
          dagster:
            asset_key: ["medias", "nytimes_articles"]
      - name: post_narrative_associations
        meta:
          dagster:
            asset_key: ["enrichments", "post_narrative_associations"]
      - name: user_geolocations
        meta:
          dagster:
            asset_key: ["enrichments", "user_geolocations"]
      - name: x_conversations
        meta:
          dagster:
            asset_key: ["social_networks", "x_conversations"]
      - name: x_conversation_posts
        meta:
          dagster:
            asset_key: ["social_networks", "x_conversation_posts"]
